### ISSUE TITLE
I don't know what I'm doing 

### ISSUE THREAD

**Issue by FionaH2Oman** [ProfKaltenberg/github-fundamentals-FionaThePeach-1#1]
I don't really know what I'm doing, but I'm going to keep messing around with things until I figure it out or formulate a better question that isn't just "what". 

😄 

Hopefully, I'm doing something right 🌷 🦃

**Comment by somethingabout** [comment]
You did the pull request and was even able to flag an issue - good job! Now add a new markdown file to the same repo.
